### PR TITLE
feat: obey --ignore-scripts CLI option

### LINKED ISSUE #7: Does not honour `--ignore-scripts`
Passing `--ignore-scripts` seems to have no effect, or at least doesn't do what I would expect it to do: ignore `preinstall`/`install`/`postinstall` scripts of dependencies during installation.

I noticed there is at least code for accepting the parameter, but haven't looked further yet to see where it might be getting dropped.

I also haven't looked at #6 yet to see if the refactor inadvertently fixes this.

### PR DESCRIPTION
**Pull request by rmg**
Fixes #7

### CODE REVIEW

**Review by mikesherov — CHANGES_REQUESTED** [review]
Thanks for contributing! This change is going to be a bit different.

**Comment by rmg** [comment]
Makes sense. This is just the quick'n'dirty fix I used locally to get it working on a project.

@mikesherov should opts be passed through to `config()`?

**Comment by mikesherov** [comment]
Sorry, for the short answer. I was on mobile before. Ideally the `runScript` function would early return `BB.resolve();` for that option.

Let me know if that makes sense. Also, please add a unit test to prove the functionality.

Thanks so much for contributing!

**Comment by rmg** [comment]
@mikesherov @zkat is this more in line with what you were looking for?

**Comment by mikesherov** [comment]
This is great thanks!

**Comment by rmg** [comment]
Cool. Squashed and cleaned up the commit message so it is no longer a lie, in case it is wanted as-is.

**Review by mikesherov — APPROVED** [review]
Great work. Thanks!

**Pull request merged**
