### PR TITLE
fix: strip BOM when reading JSON files

### PR DESCRIPTION
**Pull request by rmg**
fs.readFile* don't strip the BOM header, even when specifying 'utf8' as
the encoding, and JSON.parse() doesn't handle it either. There are
technically a bunch of BOM indicators, but this is the one seen most
commonly and actually appears in a number of package.json files in the
wild.

See nodejs/node#6924, nodejs/node#3040 for background.

### CODE REVIEW

**Comment by rmg** [comment]
Rebased after #6 was merged.

**Comment by rmg** [comment]
I don't have a large sample size, but it looks like among my local cache, the problem file is a singular occurrence:
```
$ find ~/.npm/_cacache/content-v2/sha1 -type file | while read f; do \
   tar -C ~/deleteme/bom --strip-components 1 -xUzf $f package/package.json \
    && file ~/deleteme/bom/package.json; \
  done | cut -d: -f2 | sort | uniq -c
2810  ASCII text
  56  ASCII text, with CRLF line terminators
   7  ASCII text, with very long lines
   1  ASCII text, with very long lines, with no line terminators
   1  HTML document text, ASCII text
   1  UTF-8 Unicode (with BOM) text
 170  UTF-8 Unicode text
   1  UTF-8 Unicode text, with CRLF line terminators
   2  UTF-8 Unicode text, with very long lines
```

**Comment by rmg** [comment]
Went hunting to see how npm does this, in case it has a clever way of handling it.. Turns out it is basically doing the same thing: https://github.com/npm/npm/blob/latest/lib/utils/parse-json.js

```js
if (content.charCodeAt(0) === 0xFEFF) {
  content = content.slice(1)
}
```

**Comment by rmg** [comment]
@zkat if this feels like deja vu.. https://github.com/npm/npm/pull/8724

**Comment by zkat** [comment]
This LGTM.

Can we get a test for it, too?

**Review by zkat — CHANGES_REQUESTED** [review]
Looks good, but needs a test (for all of `npm-shrinkwrap.json`, `package-lock.json`, and `package.json`, imo)

**Comment by rmg** [comment]
> Can we get a test for it, too?

Incoming. I skipped it on the first pass because every time I looked at failing file with `vim` it "helpfully" stripped the BOM for me.

> Looks good, but needs a test (for all of npm-shrinkwrap.json, package-lock.json, and package.json, imo)

Is it really necessary to test 3 different filenames in a unit test for `readJson`?

**Comment by rmg** [comment]
@zkat I've rebased and added a unit test for for `readJson`.

**Review by zkat — APPROVED** [review]

**Pull request merged**
